
services:
  db_reservatech:
    image: postgres:15
    container_name: postgres_reservatech
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: reservatech_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_reservatech
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db_reservatech

volumes:
  pgdata: